# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mockingio < Formula
  desc "mockingio is a mocking tool"
  homepage "https://github.com/mockingio/mockingio"
  version "0.0.24"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mockingio/mockingio/releases/download/v0.0.24/mockingio_v0.0.24_darwin_arm64.tar.gz"
      sha256 "53b88019f8d0a4ad609f1edde16bd8d3c85c163e4b9bdfc06bf68cfad5c1e92e"

      def install
        bin.install "mockingio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mockingio/mockingio/releases/download/v0.0.24/mockingio_v0.0.24_darwin_amd64.tar.gz"
      sha256 "524030254e6dd8e94aabebe3d80bb71ed7b31744eef7f57122fb876bdc48e086"

      def install
        bin.install "mockingio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mockingio/mockingio/releases/download/v0.0.24/mockingio_v0.0.24_linux_arm64.tar.gz"
      sha256 "3a227fd2e8cfe172d7e328f5af7629fdaca36e788e70d6f6b1d31ef1cc67e90b"

      def install
        bin.install "mockingio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mockingio/mockingio/releases/download/v0.0.24/mockingio_v0.0.24_linux_amd64.tar.gz"
      sha256 "862dff8313f61c89efce36c3db458e004817145f9f500f39b6740e4adb53f2a3"

      def install
        bin.install "mockingio"
      end
    end
  end

  test do
    system "#{bin}/mockingio --version"
  end
end
